/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas_laborales;

import Conexion.ConexionH2;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import plantillas.ExportaCatalogosHSSF;

/**
 *
 * @author ANTONIO.CORIA
 */
public class Catalogos extends javax.swing.JFrame {

    /**
     * Creates new form Catalogos
     */
    String sql="";
    ArrayList<String[]> Array;
    
    public Catalogos() {
        initComponents();
        this.setLocationRelativeTo(null);//JFRAME LOCALIZACION AL CENTRO DE LA PANTALLA
        this.getContentPane().setBackground(Color.WHITE);//JFRAME COLOR POR DEFAULT BLANCO 
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        CCat = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TCat = new javax.swing.JTable();
        ExportaEi = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ico/Logo Laborales.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        CCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CCatActionPerformed(evt);
            }
        });

        TCat.setAutoCreateRowSorter(true);
        TCat.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TCat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DESCRIPCION"
            }
        ));
        TCat.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(TCat);

        ExportaEi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ico/Exporta.png"))); // NOI18N
        ExportaEi.setToolTipText("Exportar catalogos");
        ExportaEi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportaEiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 982, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CCat, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ExportaEi, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExportaEi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ico/logo_inegi.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1006, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
     
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
CCat.addItem("TC_ACTOR");
CCat.addItem("TC_ACTOR_HUELGA");
CCat.addItem("TC_AUD_TIPO_AUDIEN");
CCat.addItem("TC_AUD_TIPO_PROCE");
CCat.addItem("TC_CAU_IMPI_ADMI_DEM");
CCat.addItem("TC_CIRCUNS_ORGANO");
CCat.addItem("TC_DEMANDADO");
CCat.addItem("TC_EDAD_TRABAJADOR");
CCat.addItem("TC_ENTIDADES");
CCat.addItem("TC_ESTATUS_DEMANDA");
CCat.addItem("TC_ESTATUS_EXPEDIENTE");
CCat.addItem("TC_EXISTENCIA_HUELGA");
CCat.addItem("TC_FASE_CONCLUSION_EJE");
CCat.addItem("TC_FASE_EXPEDIENTE");
CCat.addItem("TC_FORMA_SOLUCION");
CCat.addItem("TC_FORMA_SOLUCION_H");
CCat.addItem("TC_FORMA_SOLUCION_PH");
CCat.addItem("TC_JORNADA_TRABAJADOR");
CCat.addItem("TC_JURISDICCION");
CCat.addItem("TC_LICITUD_HUELGA");
CCat.addItem("TC_MOTIVO_PROMOCION");
CCat.addItem("TC_MOTIVO_SOLICITUD");
CCat.addItem("TC_MUNICIPIO");
CCat.addItem("TC_NAT_CONFLICTO");
CCat.addItem("TC_OCUPACION_TRABAJADOR");
CCat.addItem("TC_ORGAN_OBRERA");
CCat.addItem("TC_PROMOVENTE");
CCat.addItem("TC_RESPUESTA_SIMPLE");
CCat.addItem("TC_SECTOR_RAMA");
CCat.addItem("TC_SENTE_INCIDENTAL");
CCat.addItem("TC_SEXO_TRABAJADOR");
CCat.addItem("TC_SUBSECTOR_RAMA");
CCat.addItem("TC_TIPO_ASUNTO");
CCat.addItem("TC_TIPO_CONTRATO");
CCat.addItem("TC_TIPO_DEFENSA");
CCat.addItem("TC_TIPO_INCIDENTE");
CCat.addItem("TC_TIPO_INCOMPETENCIA");
CCat.addItem("TC_TIPO_PATRON");
CCat.addItem("TC_TIPO_SENTENCIA");
CCat.addItem("TC_TIPO_SINDICATO");
    }//GEN-LAST:event_formWindowOpened

    private void CCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CCatActionPerformed
        // TODO add your handling code here:
        //System.out.println("Cambio");
           try (Connection con = ConexionH2.getConnection();){
                   cargarJTable(TCat,Ver_catalogo(con,CCat.getSelectedItem().toString()),CCat.getSelectedItem().toString());
           } catch (SQLException ex) {
            Logger.getLogger(Catalogos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_CCatActionPerformed

    private void ExportaEiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportaEiActionPerformed
        // TODO add your handling code here:
         List<String> catalogos = Arrays.asList(
            "V3_TC_ACTORJL",
            "V3_TC_ACTOR_HUELGAJL",
            "V3_TC_AUD_TIPO_AUDIENJL",
            "V3_TC_AUD_TIPO_PROCEJL",
            "V3_TC_CAU_IMPI_ADMI_DEMJL",
            "V3_TC_CIRCUNS_ORGANOJL",
            "V3_TC_DEMANDADOJL",
            "V3_TC_EDAD_TRABAJADORJL",
            "V3_TC_ENTIDADESJL",
            "V3_TC_ESTATUS_DEMANDAJL",
            "V3_TC_ESTATUS_EXPEDIENTEJL",
            "V3_TC_EXISTENCIA_HUELGAJL",
            "V3_TC_FASE_CONCLUSION_EJEJL",
            "V3_TC_FASE_EXPEDIENTEJL",
            "V3_TC_FORMA_SOLUCIONJL",
            "V3_TC_FORMA_SOLUCION_HJL",
            "V3_TC_FORMA_SOLUCION_PHJL",
            "V3_TC_JORNADA_TRABAJADORJL",
            "V3_TC_JURISDICCIONJL",
            "V3_TC_LICITUD_HUELGAJL",
            "V3_TC_MOTIVO_PROMOCIONJL",
            "V3_TC_MOTIVO_SOLICITUDJL",
            "V3_TC_MUNICIPIOJL",
            "V3_TC_NAT_CONFLICTOJL",
            "V3_TC_OCUPACION_TRABAJADORJL",
            "V3_TC_ORGAN_OBRERAJL",
            "V3_TC_PROMOVENTEJL",
            "V3_TC_RESPUESTA_SIMPLEJL",
            "V3_TC_SECTOR_RAMAJL",
            "V3_TC_SENTE_INCIDENTALJL",
            "V3_TC_SEXO_TRABAJADORJL",
            "V3_TC_SUBSECTOR_RAMAJL",
            "V3_TC_TIPO_ASUNTOJL",
            "V3_TC_TIPO_CONTRATOJL",
            "V3_TC_TIPO_DEFENSAJL",
            "V3_TC_TIPO_INCIDENTEJL",
            "V3_TC_TIPO_INCOMPETENCIAJL",
            "V3_TC_TIPO_PATRONJL",
            "V3_TC_TIPO_SENTENCIAJL",
            "V3_TC_TIPO_SINDICATOJL"
        );
       try (Connection con = ConexionH2.getConnection()) {
    ExportaCatalogosHSSF.exportarCatalogosConDialog(
        new java.awt.Frame(),
        con,
        catalogos
    );
         JOptionPane.showMessageDialog(null, "Archivo guardado correctamente");
}       catch (SQLException ex) {
            Logger.getLogger(Catalogos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(Catalogos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ExportaEiActionPerformed

    public ArrayList<String[]> Ver_catalogo(Connection con,String Tabla){
         Array = new ArrayList<>();
        if (Tabla.equals("TC_ENTIDADES"))
        {
           // System.out.println("Entro a Catalogo entidades");       
         sql="SELECT ENTIDAD_ID,DESCRIPCION FROM V3_"+Tabla+"JL ";
         System.out.println("sql:"+sql);
        }
        if (Tabla.equals("TC_MUNICIPIO"))
        {
         sql="SELECT ENTIDAD_ID,MUNICIPIO_ID,DESCRIPCION FROM V3_"+Tabla+"JL";
        }
        if (Tabla.equals("TC_SECTOR_RAMA"))
        {
         sql="SELECT ID,REPLACE(REPLACE(DESCRIPCION,' ','_'),',','') DESCRIPCION FROM V3_"+Tabla+"JL";
        }
        if (Tabla.equals("TC_SUBSECTOR_RAMA"))
        {
         sql="SELECT ID_SECTOR,ID_SUBSECTOR,DESCRIPCION FROM V3_"+Tabla+"JL";
        }
       if ( !Tabla.equals("TC_ENTIDADES") && !Tabla.equals("TC_MUNICIPIO") && !Tabla.equals("TC_SUBSECTOR_RAMA") && !Tabla.equals("TC_SECTOR_RAMA"))
        {
         sql="SELECT ID,DESCRIPCION FROM V3_"+Tabla+"JL";   
        }
        
         try (
             PreparedStatement ps = con.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {
         if (Tabla.equals("TC_SUBSECTOR_RAMA") ||(Tabla.equals("TC_MUNICIPIO"))  ){
              while (rs.next()) {
                Array.add(new String[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3)
                });
            }
         }else{
            while (rs.next()) {
                Array.add(new String[]{
                    rs.getString(1),
                    rs.getString(2)
                });
            }
         }
        } catch (SQLException ex) {
             System.out.println( "Error al desplegar catalogo"+ ex);
        }
        return Array;
    }
    
    
public void cargarJTable(JTable tabla, ArrayList<String[]> datos,String TablaCatalogo) {

    // Encabezados
    String[] columnas;
    if (TablaCatalogo.equals("TC_SUBSECTOR_RAMA"))
    {
    columnas = new String[]{"ID_SECTOR", "ID_SUBSECTOR", "DESCRIPCION"};
    }
   else if (TablaCatalogo.equals("TC_MUNICIPIO")){
    columnas = new String[]{"ID_ENTIDAD", "ID_MUNICIPIO", "DESCRIPCION"};
    }
    else{
       columnas = new String[]{"ID", "DESCRIPCION"};
    }
    

    // Crear modelo
    DefaultTableModel modelo = new DefaultTableModel(columnas, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // tabla solo lectura
        }
    };

    // Llenar filas
    for (String[] fila : datos) {
        modelo.addRow(fila);
    }

    // Asignar modelo al JTable
    tabla.setModel(modelo);

    // Desactivar auto-ajuste
    tabla.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

    // Ajustar ancho de columnas
    if (TablaCatalogo.equals("TC_SUBSECTOR_RAMA") || TablaCatalogo.equals("TC_MUNICIPIO"))
    {
    tabla.getColumnModel().getColumn(0).setPreferredWidth(75);   // ID
    tabla.getColumnModel().getColumn(1).setPreferredWidth(75);  // DESCRIPCION  
    tabla.getColumnModel().getColumn(2).setPreferredWidth(1200);  // DESCRIPCION  
    }else{
    tabla.getColumnModel().getColumn(0).setPreferredWidth(75);   // ID
    tabla.getColumnModel().getColumn(1).setPreferredWidth(1200);  // DESCRIPCION  
    }
}

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Catalogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Catalogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Catalogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Catalogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Catalogos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CCat;
    private javax.swing.JButton ExportaEi;
    private javax.swing.JTable TCat;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
