/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas_laborales;

import Conexion.ConexionH2;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ANTONIO.CORIA
 */
public class Catalogos extends javax.swing.JFrame {

    /**
     * Creates new form Catalogos
     */
    String sql="";
    ArrayList<String[]> Array;
    
    public Catalogos() {
        initComponents();
        this.setLocationRelativeTo(null);//JFRAME LOCALIZACION AL CENTRO DE LA PANTALLA
        this.getContentPane().setBackground(Color.WHITE);//JFRAME COLOR POR DEFAULT BLANCO 
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        CCat = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TCat = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ico/Logo Laborales.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        CCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CCatActionPerformed(evt);
            }
        });

        TCat.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TCat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DESCRIPCION"
            }
        ));
        TCat.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(TCat);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(CCat, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 982, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(CCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 982, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
     
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
CCat.addItem("V3_TC_ACTORJL");
CCat.addItem("V3_TC_ACTOR_HUELGAJL");
CCat.addItem("V3_TC_AUD_TIPO_AUDIENJL");
CCat.addItem("V3_TC_AUD_TIPO_PROCEJL");
CCat.addItem("V3_TC_CAU_IMPI_ADMI_DEMJL");
CCat.addItem("V3_TC_CIRCUNS_ORGANOJL");
CCat.addItem("V3_TC_DEMANDADOJL");
CCat.addItem("V3_TC_EDAD_TRABAJADORJL");
CCat.addItem("V3_TC_ENTIDADESJL");
CCat.addItem("V3_TC_ESTATUS_DEMANDAJL");
CCat.addItem("V3_TC_ESTATUS_EXPEDIENTEJL");
CCat.addItem("V3_TC_EXISTENCIA_HUELGAJL");
CCat.addItem("V3_TC_FASE_CONCLUSION_EJEJL");
CCat.addItem("V3_TC_FASE_EXPEDIENTEJL");
CCat.addItem("V3_TC_FORMA_SOLUCIONJL");
CCat.addItem("V3_TC_FORMA_SOLUCION_HJL");
CCat.addItem("V3_TC_FORMA_SOLUCION_PHJL");
CCat.addItem("V3_TC_JORNADA_TRABAJADORJL");
CCat.addItem("V3_TC_JURISDICCIONJL");
CCat.addItem("V3_TC_LICITUD_HUELGAJL");
CCat.addItem("V3_TC_MOTIVO_PROMOCIONJL");
CCat.addItem("V3_TC_MOTIVO_SOLICITUDJL");
CCat.addItem("V3_TC_MUNICIPIOJL");
CCat.addItem("V3_TC_NAT_CONFLICTOJL");
CCat.addItem("V3_TC_OCUPACION_TRABAJADORJL");
CCat.addItem("V3_TC_ORGAN_OBRERAJL");
CCat.addItem("V3_TC_PROMOVENTEJL");
CCat.addItem("V3_TC_RESPUESTA_SIMPLEJL");
CCat.addItem("V3_TC_SECTOR_RAMAJL");
CCat.addItem("V3_TC_SENTE_INCIDENTALJL");
CCat.addItem("V3_TC_SEXO_TRABAJADORJL");
CCat.addItem("V3_TC_SUBSECTOR_RAMAJL");
CCat.addItem("V3_TC_TIPO_ASUNTOJL");
CCat.addItem("V3_TC_TIPO_CONTRATOJL");
CCat.addItem("V3_TC_TIPO_DEFENSAJL");
CCat.addItem("V3_TC_TIPO_INCIDENTEJL");
CCat.addItem("V3_TC_TIPO_INCOMPETENCIAJL");
CCat.addItem("V3_TC_TIPO_PATRONJL");
CCat.addItem("V3_TC_TIPO_SENTENCIAJL");
CCat.addItem("V3_TC_TIPO_SINDICATOJL");
    }//GEN-LAST:event_formWindowOpened

    private void CCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CCatActionPerformed
        // TODO add your handling code here:
        //System.out.println("Cambio");
           try (Connection con = ConexionH2.getConnection();){
                   cargarJTable(TCat,Ver_catalogo(con,CCat.getSelectedItem().toString()));
           } catch (SQLException ex) {
            Logger.getLogger(Catalogos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_CCatActionPerformed

    public ArrayList<String[]> Ver_catalogo(Connection con,String Tabla){
         Array = new ArrayList<>();
        if (Tabla.equals("V3_TC_ENTIDADESJL"))
        {
           // System.out.println("Entro a Catalogo entidades");
            
         sql="SELECT ENTIDAD_ID,DESCRIPCION FROM "+Tabla+"";
         System.out.println("sql:"+sql);
        }
        if (Tabla.equals("V3_TC_MUNICIPIOJL"))
        {
         sql="SELECT MUNICIPIO_ID,DESCRIPCION FROM "+Tabla+"";
        }
        if (Tabla.equals("V3_TC_SUBSECTOR_RAMAJL"))
        {
         sql="SELECT ID_SUBSECTOR,DESCRIPCION FROM "+Tabla+"";
        }
       if ( !Tabla.equals("V3_TC_ENTIDADESJL") && !Tabla.equals("V3_TC_MUNICIPIOJL") && !Tabla.equals("V3_TC_SUBSECTOR_RAMAJL"))
        {
         sql="SELECT ID,DESCRIPCION FROM "+Tabla+"";   
        }
        
         try (
             PreparedStatement ps = con.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {

            while (rs.next()) {
                Array.add(new String[]{
                    rs.getString(1),
                    rs.getString(2)
                });
            }

        } catch (SQLException ex) {
             System.out.println( "Error al desplegar catalogo"+ ex);
        }
        return Array;
    }
    
    
public void cargarJTable(JTable tabla, ArrayList<String[]> datos) {

    // Encabezados
    String[] columnas = {"ID", "DESCRIPCION"};

    // Crear modelo
    DefaultTableModel modelo = new DefaultTableModel(columnas, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // tabla solo lectura
        }
    };

    // Llenar filas
    for (String[] fila : datos) {
        modelo.addRow(fila);
    }

    // Asignar modelo al JTable
    tabla.setModel(modelo);

    // Desactivar auto-ajuste
    tabla.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

    // Ajustar ancho de columnas
    tabla.getColumnModel().getColumn(0).setPreferredWidth(75);   // ID
    tabla.getColumnModel().getColumn(1).setPreferredWidth(1200);  // DESCRIPCION
}

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Catalogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Catalogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Catalogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Catalogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Catalogos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CCat;
    private javax.swing.JTable TCat;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
