/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas_laborales;



import Conexion.ConexionH2;
import QuerysH2.Execute;
import java.awt.Color;
import java.awt.FileDialog;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import mx.org.Insert.BD.ReadCSV_Audiencias;
import mx.org.Insert.BD.ReadCSV_Colect_Econom;
import mx.org.Insert.BD.ReadCSV_Colectivo;
import mx.org.Insert.BD.ReadCSV_Control_expediente;
import mx.org.Insert.BD.ReadCSV_Ejecucion;
import mx.org.Insert.BD.ReadCSV_Huelga;
import mx.org.Insert.BD.ReadCSV_Individual;
import mx.org.Insert.BD.ReadCSV_Ordinario;
import mx.org.Insert.BD.ReadCSV_Paraprocesal;
import mx.org.Insert.BD.ReadCSV_Part_Act_Colect_Econom;
import mx.org.Insert.BD.ReadCSV_Part_Act_Colectivo;
import mx.org.Insert.BD.ReadCSV_Part_Act_Huelga;
import mx.org.Insert.BD.ReadCSV_Part_Act_Individual;
import mx.org.Insert.BD.ReadCSV_Part_Act_Ordinario;
import mx.org.Insert.BD.ReadCSV_Part_Dem_Colect_Econom;
import mx.org.Insert.BD.ReadCSV_Part_Dem_Colectivo;
import mx.org.Insert.BD.ReadCSV_Part_Dem_Huelga;
import mx.org.Insert.BD.ReadCSV_Part_Dem_Individual;
import mx.org.Insert.BD.ReadCSV_Part_Dem_Ordinario;
import mx.org.Insert.BD.ReadCSV_Pref_Credito;
import mx.org.Insert.BD.ReadCSV_Tercerias;
import triggers.CreaTriggers;


/**
 *
 * @author ANTONIO.CORIA
 */
public class InsertaTR extends javax.swing.JFrame {

    /**
     * Creates new form PIsnsertTMP
     */
       public static String tabla="",rutaT="",Versiones="",Periodo="",Nombre_archivo="",Directorio="",procedimiento,Carpeta="";
       public static boolean ventanaAbierta = false,Bandera=false,CarpetaArchivos=false;
       String ruta="",TexTabla="",TexProc;
       List<String> testList = new ArrayList<String>();
       List<String> testProc = new ArrayList<String>();
       ReadCSV_Audiencias ReadAud=new ReadCSV_Audiencias();
       ReadCSV_Control_expediente ReadControl=new ReadCSV_Control_expediente();
       ReadCSV_Ordinario ReadOrdinario=new ReadCSV_Ordinario();
       ReadCSV_Individual ReadIndividual=new ReadCSV_Individual();
       ReadCSV_Colectivo ReadColectivo=new ReadCSV_Colectivo();
       ReadCSV_Huelga ReadHuelga=new ReadCSV_Huelga();
       ReadCSV_Colect_Econom ReadColectEconom=new ReadCSV_Colect_Econom();
       ReadCSV_Paraprocesal ReadParaprocesal=new ReadCSV_Paraprocesal();
       ReadCSV_Ejecucion ReadEjecucion=new ReadCSV_Ejecucion();
       ReadCSV_Pref_Credito ReadPrefCredito=new ReadCSV_Pref_Credito();
       ReadCSV_Tercerias ReadTercerias=new ReadCSV_Tercerias();
       ReadCSV_Part_Act_Colect_Econom ReadPartActEconom=new ReadCSV_Part_Act_Colect_Econom();
       ReadCSV_Part_Dem_Colect_Econom ReadPartDemEconom=new ReadCSV_Part_Dem_Colect_Econom();
       ReadCSV_Part_Act_Colectivo ReadPartActColectivo=new ReadCSV_Part_Act_Colectivo();
       ReadCSV_Part_Dem_Colectivo ReadPartDemColectivo=new ReadCSV_Part_Dem_Colectivo();
       ReadCSV_Part_Act_Huelga ReadPartActHuelga=new ReadCSV_Part_Act_Huelga();
       ReadCSV_Part_Dem_Huelga ReadPartDemHuelga=new ReadCSV_Part_Dem_Huelga();
       ReadCSV_Part_Act_Individual ReadPartActIndividual=new ReadCSV_Part_Act_Individual();
       ReadCSV_Part_Dem_Individual ReadPartDemIndividual=new ReadCSV_Part_Dem_Individual();
       ReadCSV_Part_Act_Ordinario ReadPartActOrdinario=new ReadCSV_Part_Act_Ordinario();
       ReadCSV_Part_Dem_Ordinario ReadPartDemOrdinario=new ReadCSV_Part_Dem_Ordinario();
       CreaTriggers Triggers=new CreaTriggers();
    
    public InsertaTR() {
        initComponents();
        this.setLocationRelativeTo(null);//JFRAME LOCALIZACION AL CENTRO DE LA PANTALLA
        this.getContentPane().setBackground(Color.WHITE);//JFRAME COLOR POR DEFAULT BLANCO 
        jProgressBar1.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        PanelI = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        Insertar1 = new javax.swing.JButton();
        Insertar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        LNombreTabla = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Insert TMP");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        PanelI.setBackground(new java.awt.Color(255, 255, 255));
        PanelI.setBorder(javax.swing.BorderFactory.createTitledBorder("Integrar Información"));

        jTextField1.setEditable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        Insertar1.setText(".......");
        Insertar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Insertar1ActionPerformed(evt);
            }
        });

        Insertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ico/Insertar.png"))); // NOI18N
        Insertar.setText("Insertar");
        Insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarActionPerformed(evt);
            }
        });

        jLabel3.setText("Ruta Archivo:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ico/errorins.png"))); // NOI18N
        jButton1.setToolTipText("Errores de Insert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ico/Ima Menu.png"))); // NOI18N
        jButton2.setToolTipText("Consultar Catalogo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Catalogo");

        jLabel6.setText("Errores Insert");

        javax.swing.GroupLayout PanelILayout = new javax.swing.GroupLayout(PanelI);
        PanelI.setLayout(PanelILayout);
        PanelILayout.setHorizontalGroup(
            PanelILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelILayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(PanelILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelILayout.createSequentialGroup()
                        .addComponent(Insertar1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelILayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(129, 129, 129))))
            .addGroup(PanelILayout.createSequentialGroup()
                .addGroup(PanelILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelILayout.createSequentialGroup()
                        .addGroup(PanelILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelILayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel4))
                            .addGroup(PanelILayout.createSequentialGroup()
                                .addGap(265, 265, 265)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelILayout.createSequentialGroup()
                                .addGap(367, 367, 367)
                                .addComponent(jLabel6))
                            .addComponent(LNombreTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelILayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Insertar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addContainerGap())
            .addGroup(PanelILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelILayout.setVerticalGroup(
            PanelILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelILayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(PanelILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Insertar1)
                .addGap(54, 54, 54)
                .addComponent(Insertar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LNombreTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ico/Logo Laborales.png"))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Inserta BD");
        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        //PMenu menu = new PMenu();
        //menu.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
         PMenu menu = new PMenu();
         menu.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        if (!ventanaAbierta) {
          Errores_InsertTR Error = new Errores_InsertTR();
            ventanaAbierta = true;
            Error.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "La ventana de errores de insert ya está abierta.");
        }
        
             
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void InsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarActionPerformed

        new Thread(() -> {
            Valores();
       if (!jTextField1.equals(""))
       {
           int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro de Insertar todos los archivos RALAB?", "Alerta!", JOptionPane.YES_NO_OPTION);   
           if (resp == JOptionPane.YES_OPTION) {
              Execute Q =new Execute();
         try (Connection con = ConexionH2.getConnection();
              Connection conerr = ConexionH2.getConnection();) {     
                  try {
                      Q.LimpiaTablas(con);
                  } catch (SQLException ex) {
                      Logger.getLogger(InsertaTR.class.getName()).log(Level.SEVERE, null, ex);
                  }
                  
               Triggers.crearTriggerAudiencias(con);
               Triggers.crearTriggerColectEconom(con);
               Triggers.crearTriggerColectivo(con);
               Triggers.crearTriggerControlExpediente(con);
               Triggers.crearTriggerEjecucion(con);
               Triggers.crearTriggerHuelga(con);
               Triggers.crearTriggerIndividual(con);
               Triggers.crearTriggerOrdinario(con);
               Triggers.crearTriggerParaprocesal(con);
               Triggers.crearTriggerPartActColectEconom(con);
               Triggers.crearTriggerPartActColectivo(con);
               Triggers.crearTriggerPartActHuelga(con);
               Triggers.crearTriggerPartActIndividual(con);
               Triggers.crearTriggerPartActOrdinario(con);
               Triggers.crearTriggerPartDemColectEconom(con);
               Triggers.crearTriggerPartDemColectivo(con);
               Triggers.crearTriggerPartDemHuelga(con);
               Triggers.crearTriggerPartDemIndividual(con);
               Triggers.crearTriggerPartDemOrdinario(con);
               Triggers.crearTriggerPrefCredito(con);
               Triggers.crearTriggerTercerias(con);
               jProgressBar1.setVisible(true);   
               LNombreTabla.setText("Insertando...TR_CONTROL_EXPEDIENTE");
               jProgressBar1.setValue(5);
               ReadControl.Read_ControlExpediente(con,conerr);
               
               LNombreTabla.setText("Insertando..TR_AUDIENCIAS");
               jProgressBar1.setValue(10); 
               ReadAud.Read_Audiencias(con,conerr);
              
                LNombreTabla.setText("Insertando..TR_ORDINARIO");
               jProgressBar1.setValue(15); 
               ReadOrdinario.Read_Ordinario(con,conerr);
                
                 LNombreTabla.setText("Insertando..TR_PART_ACT_ORDINARIO");
               jProgressBar1.setValue(20); 
               ReadPartActOrdinario.Read_Part_Act_Ordinario(con,conerr);
                
               LNombreTabla.setText("Insertando..TR_PART_DEM_ORDINARIO");
               jProgressBar1.setValue(25); 
               ReadPartDemOrdinario.Read_Part_Dem_Ordinario(con,conerr);
                
                 LNombreTabla.setText("Insertando..TR_INDIVIDUAL");
               jProgressBar1.setValue(30); 
               ReadIndividual.Read_Individual(con,conerr);
                
                  LNombreTabla.setText("Insertando..TR_PART_ACT_INDIVIDUAL");
               jProgressBar1.setValue(35); 
               ReadPartActIndividual.Read_Part_Act_Individual(con,conerr);
                
                LNombreTabla.setText("Insertando..TR_PART_DEM_INDIVIDUAL");
               jProgressBar1.setValue(40); 
               ReadPartDemIndividual.Read_Part_Dem_Individual(con,conerr);
                
                LNombreTabla.setText("Insertando..TR_COLECTIVO");
               jProgressBar1.setValue(45); 
               ReadColectivo.Read_Colectivo(con,conerr);
                
               LNombreTabla.setText("Insertando..TR_PART_ACT_COLECTIVO");
               jProgressBar1.setValue(50); 
               ReadPartActColectivo.Read_Part_Act_Colectivo(con,conerr);
               
               LNombreTabla.setText("Insertando..TR_PART_DEM_COLECTIVO");
               jProgressBar1.setValue(55); 
               ReadPartDemColectivo.Read_Part_Dem_Colectivo(con,conerr);
                
               LNombreTabla.setText("Insertando..TR_HUELGA");
               jProgressBar1.setValue(60); 
                ReadHuelga.Read_Huelga(con,conerr);
               
               LNombreTabla.setText("Insertando..TR_PART_ACT_HUELGA");
               jProgressBar1.setValue(65); 
                ReadPartActHuelga.Read_Part_Act_Huelga(con,conerr);
                
                
               LNombreTabla.setText("Insertando..TR_PART_DEM_HUELGA");
               jProgressBar1.setValue(70); 
                ReadPartDemHuelga.Read_Part_Dem_Huelga(con,conerr);
                
                LNombreTabla.setText("Insertando..TR_COLECT_ECONOM");
               jProgressBar1.setValue(75);
               ReadColectEconom.Read_Colect_Econom(con,conerr);
                
               LNombreTabla.setText("Insertando..TR_PART_ACT_COLECT_ECONOM");
               jProgressBar1.setValue(80);
               ReadPartActEconom.Read_Part_Act_Colect_Econom(con,conerr);
                
                LNombreTabla.setText("Insertando..TR_PART_DEM_COLECT_ECONOM");
               jProgressBar1.setValue(85);
               ReadPartDemEconom.Read_Part_Dem_Colect_Econom(con,conerr);
                 
                 LNombreTabla.setText("Insertando..TR_PARAPROCESAL");
               jProgressBar1.setValue(90);
               ReadParaprocesal.Read_Paraprocesal(con,conerr);
                
                LNombreTabla.setText("Insertando..TR_PREFCREDITO");
               jProgressBar1.setValue(92);
               ReadPrefCredito.Read_Pref_Credito(con,conerr);
                
                 LNombreTabla.setText("Insertando..TR_TERCERIAS");
               jProgressBar1.setValue(94);
              ReadTercerias.Read_Tercerias(con,conerr);
                
                LNombreTabla.setText("Insertando..TR_EJECUCION");
               ReadEjecucion.Read_Ejecucion(con,conerr);
                 jProgressBar1.setValue(100);
                
                 jProgressBar1.setVisible(false); 
                 LNombreTabla.setText("");
                JOptionPane.showMessageDialog(null, "Registros Insertados, Favor de revisar ventana -*Errores de insert*-");
                Insertar.setEnabled(true);
            } catch (IOException ex) {
                Logger.getLogger(InsertaTR.class.getName()).log(Level.SEVERE, null, ex);
            }  catch (SQLException ex) {
                   Logger.getLogger(InsertaTR.class.getName()).log(Level.SEVERE, null, ex);
         }
         jTextField1.setText("");
           }
       }else{
            JOptionPane.showMessageDialog(null, "Favor de seleccionar carpeta Raiz");
       } 
       }).start();
         
    }//GEN-LAST:event_InsertarActionPerformed

    private void Insertar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Insertar1ActionPerformed
        // TODO add your handling code here:
        FileDialog dialogoArchivo;
        dialogoArchivo = new FileDialog(this, "ARCHIVOS LABORALES",FileDialog.LOAD);
        dialogoArchivo.setVisible(true);
        if(dialogoArchivo.getFile()!=null){ /* Validar que se haya Seleccionado un Archivo*/
            String directorio = dialogoArchivo.getDirectory();
            String nombreArchivo =dialogoArchivo.getFile();
            Nombre_archivo=nombreArchivo;
            Directorio=directorio;
            jTextField1.setText(Directorio); 
           ruta = jTextField1.getText();
            Valores();
        }
        else
        System.out.println("NO SELECCIONO ARCHIVO");

    }//GEN-LAST:event_Insertar1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Catalogos cat=new Catalogos();
        cat.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    public void Valores(){
          rutaT=jTextField1.getText();
          CarpetaArchivos=true;
        System.out.println(tabla+ruta+Versiones);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertaTR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertaTR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertaTR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertaTR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertaTR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Insertar;
    private javax.swing.JButton Insertar1;
    private javax.swing.JLabel LNombreTabla;
    public static javax.swing.JPanel PanelI;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
